[versions]
agp = "8.12.0-alpha03"
android-minSdk = "23"
android-compileSdk = "36"
android-buildToolsVersion = "36.0.0"
android-ndkVersion = "29.0.13113456"
lib-version = "1.0.1"

kotlin = "2.2.0-RC"
rules = "1.7.0-alpha03"
runner = "1.7.0-alpha03"

[libraries]
androidx-rules = { module = "androidx.test:rules", version.ref = "rules" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
