{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kyant",
    "module": "taglib",
    "version": "73139ef",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "taglib-73139ef.aar",
          "url": "taglib-73139ef.aar",
          "size": 1587327,
          "sha512": "1716491c44f493c27b1926dfec212fc6eff7814e7bf34a7208644b1a4abf1ef8a26f790b37b5f38c0e10498ba784bb8bdda80e62a8acfa3baa776390b8f906f8",
          "sha256": "0f9122d5097ad41f96ffe749806e33fb0709b25e1b72e767aaed86b363b1d236",
          "sha1": "2570c59c37c651cec9d5e189a6b458465a8d9686",
          "md5": "e267445d1f2c4aaa20eac65f80653782"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "taglib-73139ef.aar",
          "url": "taglib-73139ef.aar",
          "size": 1587327,
          "sha512": "1716491c44f493c27b1926dfec212fc6eff7814e7bf34a7208644b1a4abf1ef8a26f790b37b5f38c0e10498ba784bb8bdda80e62a8acfa3baa776390b8f906f8",
          "sha256": "0f9122d5097ad41f96ffe749806e33fb0709b25e1b72e767aaed86b363b1d236",
          "sha1": "2570c59c37c651cec9d5e189a6b458465a8d9686",
          "md5": "e267445d1f2c4aaa20eac65f80653782"
        }
      ]
    }
  ]
}
