{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kyant",
    "module": "taglib",
    "version": "rolling",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "taglib-rolling.aar",
          "url": "taglib-rolling.aar",
          "size": 1742460,
          "sha512": "bc9373a2c8b27e2c82fb49018dfdefc60fa5c3db6f01111fc178836d32b70f6359003ded31d7e57717d6881156d579dd36d0fe882f35c47fb536ee404b3c157d",
          "sha256": "8212007abd938cab6304b1b610eaeecb795c3326cccd95c6c206572737c86f34",
          "sha1": "abc637b6b671d4d629c4e98bc2e2648bf377d8da",
          "md5": "cbb862fee5458610f51073ee6c1a2266"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "taglib-rolling.aar",
          "url": "taglib-rolling.aar",
          "size": 1742460,
          "sha512": "bc9373a2c8b27e2c82fb49018dfdefc60fa5c3db6f01111fc178836d32b70f6359003ded31d7e57717d6881156d579dd36d0fe882f35c47fb536ee404b3c157d",
          "sha256": "8212007abd938cab6304b1b610eaeecb795c3326cccd95c6c206572737c86f34",
          "sha1": "abc637b6b671d4d629c4e98bc2e2648bf377d8da",
          "md5": "cbb862fee5458610f51073ee6c1a2266"
        }
      ]
    }
  ]
}
