{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kyant",
    "module": "taglib",
    "version": "rolling",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0-milestone-5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "taglib-rolling.aar",
          "url": "taglib-rolling.aar",
          "size": 1608973,
          "sha512": "28d5e0e4ac2488932904b802e865cf9a977a8f29a6d4fb2d283050cd883d23ee4f661d766d0c069d69e450bb013aff109c5e86ab258bbc384d22b2744f39a119",
          "sha256": "26fd1471a5ad94c02ce40f47ba6b07749b66418c6fea43096f0b54cbe7979ba6",
          "sha1": "66233cb3936ee4197cb8a5eb91eec5ace6f3261c",
          "md5": "b532a5d1827eb0f85771efc07d333c41"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "taglib-rolling.aar",
          "url": "taglib-rolling.aar",
          "size": 1608973,
          "sha512": "28d5e0e4ac2488932904b802e865cf9a977a8f29a6d4fb2d283050cd883d23ee4f661d766d0c069d69e450bb013aff109c5e86ab258bbc384d22b2744f39a119",
          "sha256": "26fd1471a5ad94c02ce40f47ba6b07749b66418c6fea43096f0b54cbe7979ba6",
          "sha1": "66233cb3936ee4197cb8a5eb91eec5ace6f3261c",
          "md5": "b532a5d1827eb0f85771efc07d333c41"
        }
      ]
    }
  ]
}
