{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kyant",
    "module": "taglib",
    "version": "rolling",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "taglib-rolling.aar",
          "url": "taglib-rolling.aar",
          "size": 1609828,
          "sha512": "56f317a96c4c59f2e01199e990bb560e8f28794ca3fb0ca0f7a5c60933e4cc87e1336a043eda84fc58da7bcd4b3fb650fd5d7749b9eca82c03f287a1e414d0f2",
          "sha256": "49a04d999a7f92e720251f9d0373cddf33b4eff5447d2a0f77ada4af7122cb83",
          "sha1": "e5de3e125b5a4537fd9146c4791f0230fde1cfb5",
          "md5": "c990bcea6b7ea520d7bfd9c0232c8577"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "taglib-rolling.aar",
          "url": "taglib-rolling.aar",
          "size": 1609828,
          "sha512": "56f317a96c4c59f2e01199e990bb560e8f28794ca3fb0ca0f7a5c60933e4cc87e1336a043eda84fc58da7bcd4b3fb650fd5d7749b9eca82c03f287a1e414d0f2",
          "sha256": "49a04d999a7f92e720251f9d0373cddf33b4eff5447d2a0f77ada4af7122cb83",
          "sha1": "e5de3e125b5a4537fd9146c4791f0230fde1cfb5",
          "md5": "c990bcea6b7ea520d7bfd9c0232c8577"
        }
      ]
    }
  ]
}
