{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kyant",
    "module": "taglib",
    "version": "0651835",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "taglib-0651835.aar",
          "url": "taglib-0651835.aar",
          "size": 1589657,
          "sha512": "49b81c5a5de09837d208d985613d178f735595f0f57406c30b209d6d093e9e9def7d23fbdaaa82c7fb16ad55b110225988d8aea0c1d0fb38239daea75721d267",
          "sha256": "6c080e07fbad35b6772742218e0e69f8a47a0388f937d73a5c5dc9bcf7255c7f",
          "sha1": "d80496991ce752e0b844414897d2e11cbf82f62c",
          "md5": "2e814290077f1d61b0a02875e8f50e9d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "taglib-0651835.aar",
          "url": "taglib-0651835.aar",
          "size": 1589657,
          "sha512": "49b81c5a5de09837d208d985613d178f735595f0f57406c30b209d6d093e9e9def7d23fbdaaa82c7fb16ad55b110225988d8aea0c1d0fb38239daea75721d267",
          "sha256": "6c080e07fbad35b6772742218e0e69f8a47a0388f937d73a5c5dc9bcf7255c7f",
          "sha1": "d80496991ce752e0b844414897d2e11cbf82f62c",
          "md5": "2e814290077f1d61b0a02875e8f50e9d"
        }
      ]
    }
  ]
}
