{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kyant",
    "module": "taglib",
    "version": "91f971f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0-milestone-5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "taglib-91f971f.aar",
          "url": "taglib-91f971f.aar",
          "size": 1592009,
          "sha512": "60319b539bb563e9fe6c9f8526aceb956420dde4e9b5d2543ce9ef177fb06ef99517d2b8563f271cf7d7977e2c4b20cde679670e92ccbafc9368e9fbb5395504",
          "sha256": "52e23a95bcfe3c17cddb13c9077e202901ee9cbfaa137eebffc6075e3ce00d18",
          "sha1": "1411785bcb0d04d94a7076279c11095b2077494f",
          "md5": "32e5ca28092cdebe727e558b72a24f5f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "taglib-91f971f.aar",
          "url": "taglib-91f971f.aar",
          "size": 1592009,
          "sha512": "60319b539bb563e9fe6c9f8526aceb956420dde4e9b5d2543ce9ef177fb06ef99517d2b8563f271cf7d7977e2c4b20cde679670e92ccbafc9368e9fbb5395504",
          "sha256": "52e23a95bcfe3c17cddb13c9077e202901ee9cbfaa137eebffc6075e3ce00d18",
          "sha1": "1411785bcb0d04d94a7076279c11095b2077494f",
          "md5": "32e5ca28092cdebe727e558b72a24f5f"
        }
      ]
    }
  ]
}
