name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    if: >
      ${{ github.actor != 'dependabot[bot]' && (github.event_name == 'push' || github.event_name == 'pull_request') }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      
      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-cleanup: on-success
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Android accept licenses
        uses: SimonMarquis/android-accept-licenses@v1
        
      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish to local GitHub Pages Maven repo folder
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: ./gradlew publishReleasePublicationToGitHubPagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/gh-pages-repo
